### ISSUE TITLE
rotate mesh to fit plane

### ISSUE THREAD

**Issue by danivelikova** [3DLIRIOUS/MeshLabXML#16]
Hi,
I want to rotate a mesh so that it fits to the XY plane. In Meshlab I do this like:

![image](https://user-images.githubusercontent.com/14922785/59287186-2bf7d000-8c3f-11e9-9a6a-1cb76b882829.png)

How can I do it using MeshLabXML?

Thanks

**Comment by 3DLIRIOUS** [comment]
I just added the transform.rotate_to_plane function, but haven't tested it yet. Please feel free to try it out and report back.
