### ISSUE TITLE
Implementing Surface Reconstruction; Ball Pivoting 

### ISSUE THREAD

**Issue by BKillen05** [3DLIRIOUS/MeshLabXML#18]
Hi,

Thanks for developing and releasing such a nice tool. I've been trying to do some things in VTK for a couple of months and have been able to figure it out and get it working in a couple of hours in meshlabxml.

I have been trying to fit a surface to a set of points cloud, I can do so in the GUI using the following:
1. Compute normals for point set
2. Surface Reconstruction: Ball Pivoting

I have only been able to find the Poisson implementation in meshlabxml, is there anyway I can access surface reconstruction: Ball Pivoting in meshlabxml ? Alternatively is there any guideance you can provide for me implementing this ?

Thank you in advance for any advice

Best
Bryce

**Comment by 3DLIRIOUS** [comment]
I have not implemented that filter yet, but will try to do so in the next couple of days.

**Comment by BKillen05** [comment]
Okay, thanks for the quick reply. That would be fantastic.

Thank you
Bryce

**Comment by 3DLIRIOUS** [comment]
Just committed the change to add this filter.

**Comment by BKillen05** [comment]
Awesome ! Thanks again for the great turn around and great tool.
