### ISSUE TITLE
Import any kind of file.

### ISSUE THREAD

**Issue by MohamadZohoori** [3DLIRIOUS/MeshLabXML#19]
Hi,

How can I import any kind of file like .stl mesh or .xyz mesh in my python script to apply filters and make the necessary changes on it?

Please send me the script. Because I did not find it in the documentations.

Thanks in advance for your help.

Mohamad

**Comment by 3DLIRIOUS** [comment]
You define input files in the file_in parameter to the FilterScript class or the mlx.run function.
