### ISSUE TITLE
vertices color to texture

### ISSUE THREAD

**Issue by tobyclh** [3DLIRIOUS/MeshLabXML#2]
Hello, Thanks for the great work,
in transfer.py, the vc2tex function,
It should not return the layers as they are not given in the argument nor defined anywhere (unless I am mistaken
Looking forward to support to 2016! 
:beers:

**Comment by 3DLIRIOUS** [comment]
You are quite right; these return values were left over from an earlier attempt to track MeshLab's layer stack. This is now implemented much better in the FilterScript attribute layer_stack. Most of the modules have now been refactored to use the FilterScript class, however there are a few I haven't completed yet, including transfer. Until I compete that, I scrubbed the remaining functions of any references to current_layer and last_layer; the changes are in the latest commit.

All of the filters should work with MeshLab 2016.12 (except for surface_poisson, which has been replaced with surface_poisson_screened). If you find any other filters that don't work, please raise an issue!
