### ISSUE TITLE
How to use ball pivoting?

### ISSUE THREAD

**Issue by Zhangsihao-Yang** [3DLIRIOUS/MeshLabXML#20]
I was trying to reconstruct the mesh from a point cloud and would like to use ball pivoting in my code. 
How can I write the code?

**Comment by Zhangsihao-Yang** [comment]
![1](https://user-images.githubusercontent.com/29811853/67534418-df0f1600-f682-11e9-8efe-02a5be33c4dd.png)

**Comment by 3DLIRIOUS** [comment]
Are you running the latest version from GitHub? The version on PyPI doesn't have ball pivoting yet. I can try to update that soon.

**Comment by Zhangsihao-Yang** [comment]
I see. So how can I running the latest version from GIrHub?

**Comment by 3DLIRIOUS** [comment]
You can install the github version using PIP:

`pip install -e git+git://github.com/3DLIRIOUS/MeshLabXML#egg=MeshLabXML`

Yes, MeshLab must be installed, as MeshLabXML is primarily a front end to meshlabserver.
