### ISSUE TITLE
Can I "script" the align functionality from MeshLab?

### ISSUE THREAD

**Issue by sklipnoty** [3DLIRIOUS/MeshLabXML#32]
It is not present under the filters, as far as I saw. 

Basically I want to glue all visible meshes and run icp and then merge the result.

**Comment by 3DLIRIOUS** [comment]
Sorry, this is not possible with MLX, as it can only work with filters. You might try [PyMeshLab](https://github.com/cnr-isti-vclab/PyMeshLab), as it has a deeper integration with MeshLab.
